### ISSUE TITLE
error running precompiled bundles (.app)

### ISSUE THREAD

**Issue by siftuser** [ydkhatri/mac_apt#32]
Tried running both v0.5 & 0.4 on Mac OS 10.14.6 ... but ended up with a fatal error (python runtime not located) 

Appreciate help :)

**Comment by ydkhatri** [comment]
0.4 has problems, so don't use that. The current v0.5 bundles are compiled with macOS 10.15.4 (latest). I will try to compile 0.5 on an older macOS version (and on older hardware), as the compiled version is not backward compatible. With macOS, it is both hardware and os version dependent!

**Comment by siftuser** [comment]
Thanks!

**Comment by ydkhatri** [comment]
In the meanwhile, try running from code using the install script. [https://github.com/ydkhatri/mac_apt/wiki/Installation-for-Python3.7#macos-osx](https://github.com/ydkhatri/mac_apt/wiki/Installation-for-Python3.7#macos-osx)

**Comment by siftuser** [comment]
Thanks! trying ...

**Comment by siftuser** [comment]
@ydkhatri I was able to run on live system as expected. However, when tried running on collected artifacts using following command ... but there is no out output file. Appreciate help in advance!

`python3 mac_apt_artifact_only.py -i ~/Downloads/q2data/  -o ~/Downloads -c QUARANTINE`

**Comment by ydkhatri** [comment]
Can you paste the entire output here? Also for the Quarantine plugin in ArtifactOnly mode, you need to provide path to one or more Quarantine sqlite databases as input to process. It is expecting path to end in an sqlite file, not a folder.

For any plugin, you can run --plugin_help to see what each plugin expects.

```
$ python mac_apt_artifact_only.py --plugin_help QUARANTINE

Help for Module QUARANTINE (Quarantine)

--------------------------------------------------
Provide one or more Quarantine sqlite databases as input to process. These are typically located at 
/Users/$USER/Library/Preferences/com.apple.LaunchServices.QuarantineEventsV2

```

**Comment by siftuser** [comment]
Thanks! Here is the command & output. Just a logfile is created, same as the output pasted here

`python3 mac_apt_artifact_only.py -i ~/Downloads/q2data/com.apple.LaunchServices.QuarantineEventsV2  -o ~/Downloads -c QUARANTINE`

```
Output path was : /Users/user/Downloads
MAIN-INFO-Started macOS Artifact Parsing Tool - Artifact Only mode, version 0.5
MAIN-INFO-Dates and times are in UTC unless the specific artifact being parsed saves it as local time!
MAIN-INFO-Pytsk version  = 20170801
MAIN-INFO-Pyewf version  = 20140807
MAIN-INFO-Pyvmdk version = 20181227
MAIN-INFO-PyAFF4 version = 0.33
MAIN-INFO---------------------------------------------------
MAIN-INFO-Running plugin QUARANTINE
MAIN-INFO---------------------------------------------------
MAIN.QUARANTINE-INFO-Module Started as standalone
MAIN-INFO---------------------------------------------------
MAIN-INFO-Finished in time = 00:00:00
MAIN-INFO-Review the Log file and report any ERRORs or EXCEPTIONS to the developers
```

**Comment by ydkhatri** [comment]
OK, so it's as expected. Try with a quarantine database.

**Comment by siftuser** [comment]
sorry didn't quite understand by `quarantine database` ? anything other than `com.apple.LaunchServices.QuarantineEventsV2` ?

**Comment by ydkhatri** [comment]
Oh, never mind, this was a silly bug. I just checked in a new version of quarantine.py in the plugins folder. Can you replace your file with this one? The code was rejecting any file that did not end in .sqlite. This is now fixed. Thanks for letting me know.

**Comment by siftuser** [comment]
Thanks! it worked after adding `.sqlite` extension.

FYI (not a biggy though) - I replaced old `quarantine.py` with the new one. However this did not resolve the issue ... new quarantine.py also worked after adding `.sqlite` extn

**Comment by ydkhatri** [comment]
Well, all traces of string `.sqlite` have been removed now, so I'm guessing you didn't replace the file in the right location. Anyways, let me know if you run into any other issues. I will try to create mac bundles later today.

**Comment by siftuser** [comment]
Thank you!
