### ISSUE TITLE
plugins/helpers/writer.py", line 643, in __del__ ValueError: ExcelWriter destructor, Dear coder, you forgot to close file.

### ISSUE THREAD

**Issue by jwang3417** [ydkhatri/mac_apt#41]
I was trying recover auto-sync-deleted iCloud notes from my MacBook Pro(Mojave).
Follow the tutorial to install on my mac: 

  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
     sudo chown -R $(whoami) /usr/local/bin /usr/local/lib /usr/local/sbin
     chmod u+w /usr/local/bin /usr/local/lib /usr/local/sbin
     brew install python3 git
    sudo pip3 install --upgrade virtualenv
   git clone --recursive https://github.com/ydkhatri/pylzfse
    cd pylzfse
    python setup.py build
    python setup.py install
    pip3 install pytsk3==20170802 libvmdk-python==20181227

   tar xfz ./libewf-20140808.tar.gz
   cd libewf-20140808
   python setup.py build
   python setup.py install
   pip install biplist construct==2.9.45 xlsxwriter plistutils kaitaistruct lz4 pycryptodome cryptography pybindgen==0.21.0 pillow
   cd ..
   sudo pip3 install pyaff4-0.31-yk.zip
   git clone https://github.com/libyal/libewf-legacy/
   cd libewf-20140808
   python3 setup.py build
   sudo python3 setup.py install
   cd
   cd mac_apt/
   source env/bin/activate

(env) jianw-mbp:mac_apt jianw$ cp /Users/jianw/Library/Group\ Containers/group.com.apple.notes/NoteStore.sqlite ~/Desktop/

(env) jianw-mbp:mac_apt jianw$  python ./mac_apt.py  -x  -o output E01  /Users/jianw/Desktop/NoteStore.sqlite   NOTES -l DEBUG
Output path was : /Users/jianw/mac_apt/output
MAIN-INFO-Started macOS Artifact Parsing Tool, version 0.6
MAIN-INFO-Dates and times are in UTC unless the specific artifact being parsed saves it as local time!
MAIN-DEBUG-./mac_apt.py -x -o output E01 /Users/jianw/Desktop/NoteStore.sqlite NOTES -l DEBUG
MAIN-INFO-Pytsk version  = 20170801
MAIN-INFO-Pyewf version  = 20140808
MAIN-INFO-Pyvmdk version = 20181227
MAIN-INFO-PyAFF4 version = 0.31
MAIN-ERROR-Failed to load image. Error Details are: pyewf_glob: unable to glob filenames. libewf_glob: invalid filename - missing extension.

Exception ignored in: <function SqliteWriter.__del__ at 0x105a95f80>
Traceback (most recent call last):
  File "/Users/jianw/mac_apt/plugins/helpers/writer.py", line 402, in __del__
ValueError: SqliteWriter destructor, Dear coder, you forgot to close db.
Exception ignored in: <function ExcelWriter.__del__ at 0x105a98b00>
Traceback (most recent call last):
  File "/Users/jianw/mac_apt/plugins/helpers/writer.py", line 643, in __del__
ValueError: ExcelWriter destructor, Dear coder, you forgot to close file.

(env) jianw-mbp:mac_apt jianw$  ls -lrt ./output
total 8
drwxr-xr-x  3 jianw  staff   96 Jun  1 20:06 Export
-rw-r--r--  1 jianw  staff    0 Jun  1 20:06 mac_apt.db
-rw-r--r--  1 jianw  staff  697 Jun  1 20:06 Log.20200601-200610.txt

I rename the sqlite file to txt in order to upload.
[NoteStore.sqlite.txt](https://github.com/ydkhatri/mac_apt/files/4714533/NoteStore.sqlite.txt)

**Comment by jwang3417** [comment]
Tried using direct query  as from : https://www.swiftforensics.com/2018/02/reading-notes-database-on-macos.html
Empty output as well. 
Any help would be really appreciated!


(env) jianw-mbp:Desktop jianw$ sqlite3  ./NoteStore.sqlite
SQLite version 3.24.0 2018-06-04 14:10:15
Enter ".help" for usage hints.
sqlite> list
   ...> help
   ...>
   ...> SELECT n.Z_PK, n.ZNOTE as note_id, n.ZDATA as data,c3.ZFILESIZE,c4.ZFILENAME, c4.ZIDENTIFIER as att_uuid,c1.ZTITLE1 as title, c1.ZSNIPPET as snippet, c1.ZIDENTIFIER as noteID,datetime(c1.ZCREATIONDATE1, 'unixepoch') as created, datetime(c1.ZLASTVIEWEDMODIFICATIONDATE, 'unixepoch'), datetime(c1.ZMODIFICATIONDATE1, 'unixepoch') as modified,c2.ZACCOUNT3, c2.ZTITLE2 as folderName, c2.ZIDENTIFIER as folderID,c5.ZNAME as acc_name, c5.ZIDENTIFIER as acc_identifier, c5.ZACCOUNTTYPEFROM ZICNOTEDATA as nLEFT JOIN ZICCLOUDSYNCINGOBJECT as c1 ON c1.ZNOTEDATA = n.Z_PKLEFT JOIN ZICCLOUDSYNCINGOBJECT as c2 ON c2.Z_PK = c1.ZFOLDERLEFT JOIN ZICCLOUDSYNCINGOBJECT as c3 ON c3.ZNOTE= n.ZNOTELEFT JOIN ZICCLOUDSYNCINGOBJECT as c4 ON c4.ZATTACHMENT1= c3.Z_PKLEFT JOIN ZICCLOUDSYNCINGOBJECT as c5 ON c5.Z_PK = c1.ZACCOUNT2ORDER BY note_id
   ...>
   ...>

**Comment by ydkhatri** [comment]
OK, thanks for sharing the database. I will take a look and let you know. 

Also, you are using the wrong script. **mac_apt.py** is for full disk images. You want to use **mac_apt_artifact_only.py** to process single artifact files. You would run it as below:
```
python ./mac_apt_artifact_only.py -x -o output -l DEBUG -i /Users/jianw/Desktop/NoteStore.sqlite NOTES 
```

**Comment by ydkhatri** [comment]
So, with the command above, I was able to run and extract 8 notes from it. However, the database does not have any notes with content in them.

**Comment by jwang3417** [comment]
> So, with the command above, I was able to run and extract 8 notes from it. However, the database does not have any notes with content in them.

Thank you so much for your prompt help.
I guess 8 notes is my offline notes which I stored locally. I had ~100 notes before wiped out.  

Do you think 
  /Users/jianw/Library/Containers/com.apple.Notes/Data/Library/Notes/NotesV7.storedata
would make any difference?
https://drive.google.com/drive/folders/1mCL2snbCRizHF1fLaW1zsGGwsnL4W5Bv?usp=sharing


Seems I still have trouble running your suggested command.
   (env) jianw-mbp:mac_apt jianw$ python ./mac_apt_artifact_only.py -x -o output -l DEBUG -i /Users/jianw/Desktop/NoteStore.sqlite NOTES
   usage: mac_apt_artifact_only.py [-h] [-i INPUT_PATH [INPUT_PATH ...]]
                                [-o OUTPUT_PATH] [-x] [-c] [-l LOG_LEVEL]
                                [--plugin_help]
                                plugin
   mac_apt_artifact_only.py: error: the following arguments are required: plugin

**Comment by ydkhatri** [comment]
This one is empty. Were there any files with the same name but ending in **-wal** or **-journal** in the same folder? If so, the data you are looking for may be there. 

I fixed my command in above comment. Here it is again. The script needs -i and -o parameters first.
```
python ./mac_apt_artifact_only.py -i /Users/jianw/Desktop/NoteStore.sqlite -o output -x -l DEBUG  NOTES 
```

**Comment by jwang3417** [comment]
Thanks a lot for your time. That is very helpful. 
The command line really worked for my NoteStore.sqlite, although it seems still not work for NoteStore.sqlite-wal  file. 

(env) jianw-mbp:mac_apt jianw$ python ./mac_apt_artifact_only.py -i /Users/jianw/Downloads/NoteStore.sqlite-wal    -o output2 -x -l DEBUG  NOTES
Output path was : output2
MAIN-INFO-Started macOS Artifact Parsing Tool - Artifact Only mode, version 0.6
MAIN-INFO-Dates and times are in UTC unless the specific artifact being parsed saves it as local time!
MAIN-DEBUG-./mac_apt_artifact_only.py -i /Users/jianw/Downloads/NoteStore.sqlite-wal -o output2 -x -l DEBUG NOTES
MAIN-DEBUG-Trying to create db @ output2/mac_apt.db
MAIN-DEBUG-Trying to create xlsx file @ output2/mac_apt.xlsx
MAIN-INFO---------------------------------------------------
MAIN-INFO-Running plugin NOTES
MAIN-INFO---------------------------------------------------
MAIN.NOTES-INFO-Module Started as standalone
MAIN.NOTES-DEBUG-Input file passed was: /Users/jianw/Downloads/NoteStore.sqlite-wal
MAIN.NOTES-INFO-Processing file /Users/jianw/Downloads/NoteStore.sqlite-wal
MAIN.NOTES-DEBUG-Opened database successfully
MAIN.NOTES-ERROR-Failed to list tables of db. Error Details:file is not a database
MAIN.NOTES-ERROR-Query  execution failed. Query was:  SELECT n.Z_PK, n.ZNOTE as note_id, n.ZDATA as data,  c3.ZFILESIZE,  c4.ZFILENAME, c4.ZIDENTIFIER as att_uuid,   c1.ZTITLE1 as title, c1.ZSNIPPET as snippet, c1.ZIDENTIFIER as noteID,  c1.ZCREATIONDATE1 as created, c1.ZLASTVIEWEDMODIFICATIONDATE, c1.ZMODIFICATIONDATE1 as modified,  c2.ZACCOUNT3, c2.ZTITLE2 as folderName, c2.ZIDENTIFIER as folderID,  c5.ZNAME as acc_name, c5.ZIDENTIFIER as acc_identifier, c5.ZACCOUNTTYPE  FROM ZICNOTEDATA as n  LEFT JOIN ZICCLOUDSYNCINGOBJECT as c1 ON c1.ZNOTEDATA = n.Z_PK   LEFT JOIN ZICCLOUDSYNCINGOBJECT as c2 ON c2.Z_PK = c1.ZFOLDER  LEFT JOIN ZICCLOUDSYNCINGOBJECT as c3 ON c3.ZNOTE= n.ZNOTE  LEFT JOIN ZICCLOUDSYNCINGOBJECT as c4 ON c4.ZATTACHMENT1= c3.Z_PK  LEFT JOIN ZICCLOUDSYNCINGOBJECT as c5 ON c5.Z_PK = c1.ZACCOUNT2   ORDER BY note_id
Traceback (most recent call last):
  File "/Users/jianw/mac_apt/plugins/notes.py", line 209, in ReadNotesHighSierra
    cursor = db.execute(query)
sqlite3.DatabaseError: file is not a database
MAIN.NOTES-INFO-No notes found in /Users/jianw/Downloads/NoteStore.sqlite-wal
MAIN-INFO---------------------------------------------------
MAIN-INFO-Finished in time = 00:00:00
MAIN-INFO-Review the Log file and report any ERRORs or EXCEPTIONS to the developers

**Comment by ydkhatri** [comment]
The -wal file is processed automatically when it is in the same folder as the main database. You cannot process it separately. Just put main database and its -wal file in the same folder, then process the main database with mac_apt.

**Comment by ydkhatri** [comment]
Closing for a lack of response!
